# Multilingual Strings System
# STRINGS[lang][key]

STRINGS = {
    'ar': {
        'START_MSG': "🌟 **أهلاً بك في بوت الربح والهدايا!** 🌟\n\nيسعدنا انضمامك إلينا. لقد حصلت على **10 نقاط** كهدية ترحيبية! 🎁\n\nاستخدم القائمة أدناه لجمع النقاط ودعوة أصدقائك للربح أكثر.",
        'PROFILE_MSG': "👤 **معلومات حسابك**\n\n🆔 **الأيدي:** `{user_id}`\n💰 **رصيدك الحالي:** `{points}` نقطة\n📅 **تاريخ الانضمام:** `{joined_at}`\n💎 **الحالة:** {status}",
        'DAILY_SUCCESS': "✅ **تم استلام هديتك اليومية!** لقد حصلت على **{amount}** نقاط.",
        'DAILY_WAIT': "⏳ **عذراً!** لقد استلمت هديتك اليومية بالفعل. يرجى المحاولة مرة أخرى بعد **24 ساعة**.",
        'INVITE_MSG': "👥 **ادعُ أصدقاءك واربح!**\n\nشارك رابط الإحالة الخاص بك مع أصدقائك. ستحصل على **5 نقاط** مقابل كل شخص يسجل عبر رابطك! 🚀\n\n🔗 **رابط الإحالة الخاص بك:**\n`{referral_link}`",
        'REFERRAL_NOTIFICATION': "🎉 **بشرى سارة!** لقد اشترك شخص ما عبر رابط الإحالة الخاص بك وحصلت على **5 نقاط!**",
        'TASKS_MENU_MSG': "🚀 **قائمة المهام المتاحة**\n\nاختر مهمة من القائمة أدناه، قم بتنفيذها وأرسل إثبات (لقطة شاشة) للحصول على النقاط! 💰",
        'TASK_DETAILS_MSG': "📽️ **تفاصيل المهمة**\n\n🔗 **الرابط:** {url}\n📝 **النوع:** {type}\n💰 **الجائزة:** {reward} نقطة\n\n⚠️ **تعليمات:**\n1. اضغط على الرابط أعلاه.\n2. قم بـ ({type}).\n3. التقط صورة للشاشة (Screenshot) تثبت ذلك.\n4. اضغط على \"إرسال الإثبات\" بالأسفل وارفع الصورة.",
        'WAIT_FOR_PROOF': "📸 **من فضلك أرسل لقطة الشاشة (الصورة) الآن كإثبات للتنفيذ:**",
        'PROOF_SUBMITTED': "✅ **تم استلام الإثبات بنجاح!**\nسيقوم المدير بمراجعته وإضافة النقاط لك فور التأكد. شكرًا لصبرك! ⏳",
        'SHOP_CURRENCY_MSG': "🛒 **متجر النقاط العالمي**\n\nمن فضلك اختر العملة التي تود الدفع بها:",
        'SHOP_PACKAGES_MSG': "📦 **الباقات المتاحة لعملة {currency}:**\n\nاختر الباقة المناسبة لك:",
        'SHOP_INSTRUCTIONS_MSG': "📝 **تعليمات الدفع ({points} نقطة):**\n\n{instructions}\n\n⚠️ **بعد التحويل، أرسل صورة الإثبات (ScreenShot) هنا فوراً.**",
        'SHOP_DEPOSIT_SUBMITTED': "✅ **تم استلام إثبات الدفع!**\nسيتم مراجعة الطلب وإضافة النقاط لحسابك فور التأكد. شكرًا لك!",
        'PROMO_MENU_MSG': "🚀 **روج لصفحتك على تيك توك**\n\nيمكنك الآن استخدام نقاطك للحصول على متابعين حقيقيين لصفحتك!\n\n1. أدخل رابط صفحتك.\n2. حدد ميزانية النقاط.\n3. حدد الجائزة لكل متابع (سيتم خصم عمولة {commission}% للمنصة).",
        'HISTORY_MSG': "📜 **سجل آخر العمليات في حسابك:**\n\n{history}",
        'USER_BANNED_MSG': "🚫 **عذراً! تم حظر حسابك من استخدام البوت.**",
        'RATE_LIMIT_MSG': "⚠️ **تمهل قليلاً!** يرجى عدم إرسال الكثير من الطلبات في وقت واحد.",
        'VIP_INFO_MSG': "💎 **عضوية VIP الاحترافية**\n\nاستمتع بمميزات حصرية:\n✅ **مضاعفة الأرباح ({multiplier}x)** من جميع المهام.\n✅ **أولوية** في مراجعة السحوبات.\n✅ **شارة مميزة** في ملفك الشخصي.\n\n💰 **سعر الاشتراك (30 يوم):** {price} نقطة.",
        'VIP_SUCCESS': "🎉 **تهانينا!** لقد أصبحت عضواً VIP الآن. استمتع بمضاعفة أرباحك!",
        'VIP_INSUFFICIENT': "❌ **عذراً!** رصيدك لا يكفي لشراء عضوية VIP.",
        'LANG_PICKER': "🌐 **الرجاء اختيار اللغة الخاصة بك / Please choose your language:**",
        'SUPPORT_MSG': "💬 **قسم الدعم الفني**\n\nأرسل رسالتك هنا وسيقوم الفريق بالرد عليك في أقرب وقت ممكن.",
        'SUPPORT_SUBMITTED': "✅ **تم إرسال رسالتك للدعم الفني!**\nيرجى الانتظار، سيصلك الرد هنا قريباً.",
        'MAINTENANCE_MSG': "🛠️ **نحن في صيانة حالياً!**\n\nنقوم ببعض التحديثات المهمة لجعل تجربتكم أفضل. سنعود للعمل قريباً جداً. شكراً لصبركم! 🙏",
        'BACKUP_SUCCESS': "💾 **تم استخراج نسخة احتياطية من قاعدة البيانات بنجاح.**",
        'REFRESH_MSG': "🔄 **جاري تحديث النظام...**\nسيتم إعادة تشغيل البوت الآن لتطبيق التعديلات."
    },
    'en': {
        'START_MSG': "🌟 **Welcome to the Rewards Bot!** 🌟\n\nWe're glad to have you. You've received **10 points** as a welcome gift! 🎁\n\nUse the menu below to collect points and invite friends to earn more.",
        'PROFILE_MSG': "👤 **Your Profile Info**\n\n🆔 **User ID:** `{user_id}`\n💰 **Current Balance:** `{points}` Points\n📅 **Joined At:** `{joined_at}`\n💎 **Status:** {status}",
        'DAILY_SUCCESS': "✅ **Daily gift received!** You got **{amount}** points.",
        'DAILY_WAIT': "⏳ **Sorry!** You've already claimed your daily gift. Try again in **24 hours**.",
        'INVITE_MSG': "👥 **Invite Friends & Win!**\n\nShare your referral link. You get **5 points** for every person who registers via your link! 🚀\n\n🔗 **Your Referral Link:**\n`{referral_link}`",
        'REFERRAL_NOTIFICATION': "🎉 **Great News!** Someone joined using your link and you earned **5 points!**",
        'TASKS_MENU_MSG': "🚀 **Available Tasks**\n\nChoose a task, complete it, and send a screenshot to get points! 💰",
        'TASK_DETAILS_MSG': "📽️ **Task Details**\n\n🔗 **Link:** {url}\n📝 **Type:** {type}\n💰 **Reward:** {reward} Points\n\n⚠️ **Instructions:**\n1. Click the link above.\n2. Complete the ({type}) task.\n3. Take a screenshot as proof.\n4. Click \"Submit Proof\" below and upload the image.",
        'WAIT_FOR_PROOF': "📸 **Please send the screenshot (image) now as proof of completion:**",
        'PROOF_SUBMITTED': "✅ **Proof received successfully!**\nThe admin will review it and add points shortly. Thanks for your patience! ⏳",
        'SHOP_CURRENCY_MSG': "🛒 **Global Points Store**\n\nPlease choose your payment currency:",
        'SHOP_PACKAGES_MSG': "📦 **Available Packages for {currency}:**\n\nSelect the best package for you:",
        'SHOP_INSTRUCTIONS_MSG': "📝 **Payment Instructions ({points} Points):**\n\n{instructions}\n\n⚠️ **After transfer, send the screenshot proof here immediately.**",
        'SHOP_DEPOSIT_SUBMITTED': "✅ **Payment proof received!**\nPoints will be added once verified. Thank you!",
        'PROMO_MENU_MSG': "🚀 **Promote Your TikTok Page**\n\nUse your points to get real followers!\n\n1. Enter your page link.\n2. Set total budget.\n3. Set reward per follower (Platform takes {commission}% commission).",
        'HISTORY_MSG': "📜 **Recent Transactions History:**\n\n{history}",
        'USER_BANNED_MSG': "🚫 **Sorry! Your account is banned.**",
        'RATE_LIMIT_MSG': "⚠️ **Slow down!** Please do not send too many requests at once.",
        'VIP_INFO_MSG': "💎 **Premium VIP Membership**\n\nEnjoy exclusive benefits:\n✅ **Double Rewards ({multiplier}x)** from all tasks.\n✅ **Priority** in withdrawal reviews.\n✅ **Special Badge** in your profile.\n\n💰 **Price (30 Days):** {price} Points.",
        'VIP_SUCCESS': "🎉 **Congratulations!** You are now a VIP member. Enjoy double earnings!",
        'VIP_INSUFFICIENT': "❌ **Sorry!** You don't have enough points for VIP membership.",
        'LANG_PICKER': "🌐 **Please choose your language:**",
        'SUPPORT_MSG': "💬 **Technical Support**\n\nSend your message here and our team will reply to you as soon as possible.",
        'SUPPORT_SUBMITTED': "✅ **Your message has been sent to support!**\nPlease wait, you will receive a reply here shortly.",
        'MAINTENANCE_MSG': "🛠️ **System Maintenance!**\n\nWe are doing some important updates. We will be back online very soon. Thank you for your patience! 🙏",
        'BACKUP_SUCCESS': "💾 **Database backup generated successfully.**",
        'REFRESH_MSG': "🔄 **Updating system...**\nThe bot will restart now to apply changes."
    }
}
